### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by lijualivenow** [ccoreilly/vosk-browser#17]
I have downloaded the Zip file from github. Examples are not working from local files or from the [glitch](https://glitch.com/
)

**Comment by ccoreilly** [comment]
Please share the steps you followed. Be aware that you need to start a server locally and cannot just open an HTML file with your browser.

As for the glitch, I am unfamiliar with that tool and cannot offer any support.

**Comment by lijualivenow** [comment]
how to run the server?

**Comment by ccoreilly** [comment]
Run one of these commands from within the examples/modern-vanilla folder:

`npx serve`

or

`python2 -m SimpleHTTPServer`

 or

`python3 -m http.server`

Good luck with the integration.

**Comment by lijualivenow** [comment]
for a web page?

**Comment by ccoreilly** [comment]
It is in `examples/react`, you'll need to update the [package.json](https://github.com/ccoreilly/vosk-browser/blob/master/examples/react/package.json#L19) to point `vosk-browser` to version 0.0.5 instead of `../../lib`. Please research a bit how javascript, node, npm and react work, I will not answer trivial questions you can answer yourself by reading the documentation of the mentioned projects or googling around.
