### ISSUE TITLE
Build broken by kaldi repo

### ISSUE THREAD

**Issue by Yahweasel** [ccoreilly/vosk-browser#23]
The kaldi repo no longer has an upstream-1.8.0 branch nor a revision 75ecaef39 (thanks, git, for allowing erasing history). Right now, vosk-browser doesn't build because of these issues.

**Comment by Yahweasel** [comment]
Correction: The commit is still there, just the branch is gone. Now I have to remember how to git checkout a specific revision...

**Comment by Yahweasel** [comment]
And the answer is that you can't. I don't understand why people use git when it's this awful.

**Comment by Yahweasel** [comment]
I made a commit to "fix" it by fetching the ZIP of the commit, but it's so awful, I'm reluctant to pull request :) . Here it is, holler if you want me to make a PR: https://github.com/ennuicastr/vosk-browser/commit/db6566ba0a9f62ed9bcd4df7b84f158996c2c9b5

**Comment by ccoreilly** [comment]
The branches were [renamed](https://github.com/alphacep/vosk-api/commit/195db43b9ef4d0e29aeb982676bb3da31e4c57b7#diff-12a031464ddf2c005ca2c58a699ad9db76337c57644963c2c170282903529b43), but I guess something got rebased because the same commit now has [another hash](https://github.com/alphacep/kaldi/commit/1e2eeb9c95c68c6ba428b00bf12ccbd01cadde47).

As you say, the [commit](https://github.com/alphacep/kaldi/commit/75ecaef39) is still in the repo so just removing the branch reference and single-branch flag should suffice. I am testing it, otherwise I will switch to the new "vosk" branch and test. I have a local copy of the repository in the working state, I wanted to avoid forking a fork and maintaining it.

**Comment by ccoreilly** [comment]
Ok, I can't checkout the commit without branch and I need to update the patch to work with the new rebased commit. I [pushed the local copy](https://github.com/ccoreilly/kaldi) I had until I can change the patch to work with the official kaldi fork of alphaceph.

I'll update the builder Dockerfile once I confirm it builds again. Thank you for noticing and letting me know!

**Comment by Yahweasel** [comment]
Yeah, simply removing those flags would _not_ work with the older hash. There is literally nothing you can do to get git to clone or fetch a commit that is not the antecedent of a living reference (branch or tag). It's infuriating.

I await a fix. I assure you, my interest in noticing is purely selfish :rofl:

**Comment by nshmyrev** [comment]
new branch is called "vosk" https://github.com/alphacep/kaldi/tree/vosk

**Comment by ccoreilly** [comment]
Thank you Nikolay. As a quick fix I pushed the old state to a repository in my handle, this can be used to build the library until I find the time to update the patch against the "vosk" branch. See [commit](https://github.com/ccoreilly/vosk-browser/commit/0cc92b06837c0223f7192fc36ce9942d06de019e).
