### ISSUE TITLE
Models not loading (downloading) in Firefox 96

### ISSUE THREAD

**Issue by gullabi** [ccoreilly/vosk-browser#40]
When load button is pushed, browser console gives the error:

```
Failed to sync file system: InvalidStateError: A mutation operation was attempted on a database that did not allow mutations. b28a5120-7502-42f6-9dd0-5e7a322b0752:117:21
    error blob:https://ccoreilly.github.io/b28a5120-7502-42f6-9dd0-5e7a322b0752:117
    handleMessage blob:https://ccoreilly.github.io/b28a5120-7502-42f6-9dd0-5e7a322b0752:166
```
and does not download the model. Tried for English and Catalan.

OS: Ubuntu 20.04

**Comment by ccoreilly** [comment]
You are referring to the [demo](https://ccoreilly.github.io/vosk-browser/) right? Vosk-browser uses IndexedDB for persisting the downloaded models, which is not available in "Incognito" mode or if you tell firefox to "never remember history".

Can that be the case? I can reproduce the issue if I force both modes. Can you confirm it works otherwise? You can also enable IndexedDB support in private mode in about:config

I guess we could fall back to temporary memory / not persisting the models if indexedDB is not available.

**Comment by gullabi** [comment]
It is correct. I have a browser which has "never remember history". 

I changed the options in about:config. To be exact I put `dom.indexedDB.privateBrowsing.enabled` to `True`, and it works. Thanks.
