### ISSUE TITLE
Online demo created

### ISSUE THREAD

**Issue by Rodeoclash** [ccoreilly/vosk-browser#48]
Not sure if this is of any use, but I created a small online demo using this tool when I was experimenting with it. You can view it online at

https://captioner.richardson.co.nz/

And the source code for it is at: https://github.com/Rodeoclash/captioner

It might be possible to adapt this for an official demo if you're interested (although it is lacking a few things at the moment, i.e. it only works on video and currently the videos have no audio when playing).

**Comment by ccoreilly** [comment]
Very nice! I am thinking of adding a section to the Readme with some examples/demos/products using the library, what do you think?

**Comment by Rodeoclash** [comment]
I think being able to try it out easily is very helpful. I'm happy if you want to point to my demo, but you might be better off forking it (or I'm happy to transfer ownership of the repo) if you want a starting point for the demo. I really hacked it together and I think it could do with a bit of polish (which I'm happy to help out with).

**Comment by TechServiceConseil** [comment]
Hey guys !

I discover your work yesterday. It's great. 
I try to run it but it's not possible in a simple way. I try several things.

First the cdn, the first thing on your repo:
 I try to run it with a single page using nodejs and that doesn't run if you put all in an index.html and open it with the computer. After spend the night on it, i think the generation of the model with a ramdom path is an big issue. On an express nodejs server the dynamic generation seems to be an issue. With the index file open in the desktop that push a url error. In each case the worker code is generate.
The two errors are  Error: HTTP error! status: 404 from the worker 0378db2c-af89-499f-877f-7f8d9a12851a:127
and TypeError: Failed to construct 'URL': Invalid base URL

Second the example in moder-vanilla, same test, same result

I test the repo of rodeoclash and it's good too

To Make the things works. Take the word example and put the modification you have doing compare to the moder-vanilla one.
To get it work i have to replace

`const sampleRate = 16000;
    
    const mediaStream = await navigator.mediaDevices.getUserMedia({
        video: false,
        audio: {
            echoCancellation: true,
            noiseSuppression: true,
            channelCount: 1,
            sampleRate
        },
    });
    const audioContext = new AudioContext();
    const source = audioContext.createMediaStreamSource(mediaStream);
    
    const recognizer = new model.KaldiRecognizer(sampleRate, JSON.stringify(['[unk]', 'encen el llum', 'apaga el llum']));
    
    recognizer.on("result", (message) => {
        const result = message.result;
        console.log(JSON.stringify(result, null, 2));
        
        const newSpan = document.createElement('span');
        newSpan.textContent = `${result.text} `;
        resultsContainer.insertBefore(newSpan, partialContainer);
    });
    recognizer.on("partialresult", (message) => {
        const partial = message.result.partial;
        console.log(JSON.stringify(message.result, null, 2));

        partialContainer.textContent = partial;
    });
    
    partialContainer.textContent = "Ready";
    

    
    const recognizerNode = audioContext.createScriptProcessor(4096, 1, 1)
    recognizerNode.onaudioprocess = (event) => {
        try {
            recognizer.acceptWaveform(event.inputBuffer)
        } catch (error) {
            console.error('acceptWaveform failed', error)
        }
    }
    source.connect(recognizerNode);`

by 

`    const sampleRate = 48000;
    
    const recognizer = new model.KaldiRecognizer(sampleRate);
    recognizer.setWords(true);

    recognizer.on("result", (message) => {
        const result = message.result;
        // console.log(JSON.stringify(result, null, 2));
        
        const newSpan = document.createElement('span');
        newSpan.textContent = `${result.text} `;
        resultsContainer.insertBefore(newSpan, partialContainer);
    });
    recognizer.on("partialresult", (message) => {
        const partial = message.result.partial;

        partialContainer.textContent = partial;
    });
    
    partialContainer.textContent = "Ready";
    
    const mediaStream = await navigator.mediaDevices.getUserMedia({
        video: false,
        audio: {
            echoCancellation: true,
            noiseSuppression: true,
            channelCount: 1,
            sampleRate
        },
    });
    
    const audioContext = new AudioContext();
    await audioContext.audioWorklet.addModule('recognizer-processor.js')
    const recognizerProcessor = new AudioWorkletNode(audioContext, 'recognizer-processor', { channelCount: 1, numberOfInputs: 1, numberOfOutputs: 1 });
    recognizerProcessor.port.postMessage({action: 'init', recognizerId: recognizer.id}, [ channel.port2 ])
    recognizerProcessor.connect(audioContext.destination);
    
    const source = audioContext.createMediaStreamSource(mediaStream);
    source.connect(recognizerProcessor);`

With that you can use express with an express server with just that in the index.js and a public folder where you put your project word-vanilla

'const express = require('express');
const path = require('path')
const app = express();
const PORT = 3300;

app.use(express.static('public'));

app.get('/public/test.html', (req, res) => {
   res.send("hello")
});

app.listen(PORT, () => console.log(`Server listening on port: ${PORT}`));'

and Voila just run node index.js of course you have to put the model you have download and set the right name in Vosk.createModel('model.tar.gz');  and add a / behing the name of the file.

You have do realy great job both of us.

I think the best is to make a folder with the js server i provide and remove your vanilla folder and the react too because you have lot of critical warning. Yoou have complicate the think with your react guys lol. Just simple express make the work far more accessible than now.

Again thank you for the job i have now a simple server wich provide the page without other language or framework so simple.
I gonna push the job a little more and gonna modify the code to connect the a websocket and so on. I used rhasspy before for my voice assistant. Now i can use to power a page where the performance of the detection is link to the devices. 

Nice job and again thank you

**Comment by ccoreilly** [comment]
The examples are meant to run in the browser, not nodejs. You need however to serve the files with a server (which you did in the end with express), you can't just open the HTML file with your browser, that is why you got the error.

**Comment by TechServiceConseil** [comment]
open with my computer was the hopeless try for me but after all why not.
What i say however still true. You can try your repo, no one work out of the box. I works on an implementation of a websocket listener  of a node-red app i run this morning. If you want i can send you the file. I just finish to handle message in and out. I plan to devellop skill with this tools. 
You are for me a prefect replacement for a part of rhasspy. I gonna respect the standard of rhasspy intent because he use a kaldi model too. So i am note sure a this point but i think i could apply them when vosk create the model. I you have more info on that part. i take it.
Since i gonna use tfjs for other stuff than the audio i think i gonna add it to handle wakeword because i am not aware of a tool that run in browser and dont need apikey.

Again thank a lot. for the stuff and sorry for my poor english.

I think i gonna have time to put that stuff in my repo tomorrow or the next day

**Comment by Rodeoclash** [comment]
@TechServiceConseil sounds like you worked it out.

If you are running this on the server then you could also take a look at https://www.npmjs.com/package/vosk which is the node bindings to use it. FYI - I've never used them, I just saw a link to it on the homepage of this repo.

**Comment by frissonlabs** [comment]
Why did the sample rate need to be updated from 16000 to 48000? Isn't VOSK compatible with 16kHz audio data?
