### ISSUE TITLE
Cant build  example/react

### ISSUE THREAD

**Issue by lmessinger** [ccoreilly/vosk-browser#6]
First thanks for an amazing contribution. 

Second, trying to build (npm run build), I get that recognizer.tsx can't find vosk-browser. Went to node_modules/vosk-browser and did npm build, which solved the first issue, but this led to others.

Any ideas?

Thanks again!

**Comment by ccoreilly** [comment]
Hi! 
The issue is that in the package.json vosk-browser has a relative path to "../../lib" as I was using that example to test changes in the library. It thus only works if you have built the library from scratch. 

You can quickly fix is by changing the package.json and giving it the version 0.0.3 instead of the relative path.

I'll push the fix myself when I'm in front of a computer.
